/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "drilling-machine": "url('/images/slider.jpg')",
        pharmacy: "url('/setup.png')",
        "bread-crumbs": "url('/images/breadcrumb-01.jpg')",
        "bread-crumb": "url('/images/Courses.jpg')",
        "vision-eye": "url('/images/Vision.jpg')",
      },
      fontFamily: {
        playfair: ["Playfair", "swap"],
        roboto: ["Roboto", "swap"],
        outfit: ["Outfit", "swap"],
      },
      colors: {
        current: "currentColor",
        silver: "#595959",
        transparent: "transparent",
        Navbar: "#0177BA",
        Darkblue: "#294057",
        purple: "#310A50",
        black: "#040007",
        darkblack: "#050108",
        offwhite: "#F0EDED",
        darkpurple: "#190627",
        cam: "#F2F2F2",
        text: "#2B2B5E",
        topbar: "#00CDE5",
        lemongreendark: "#A3D9AB",
        darklemon: "#0EBC93",
        primary: "#003509",
        darkgreen: "#057147",
        peach: "#E8878E",
        lightpeach: "#FFF8F8",
        lightpurple: "#E5E5FE",
        darkwhite: "#F7F5FF",
        white: "#FFFFFF",
        bodydark3: "#637381",
        // black: "#1C2434",
        darkgrey: "#484A58",
        darkgrey1: "#8D98AA",
        "black-2": "#010101",
        body: "#64748B",
        bodydark: "#AEB7C0",
        bodydark1: "#DEE4EE",
        bodydark2: "#8A99AF",
        secondary: "#80CAEE",
        stroke: "#E2E8F0",
        gray: "#EFF4FB",
        graydark3: "#D9D9D9",
        graydark: "#333A48",
        graydark1: "#717B8C",
        graydark2: "#4C535F",
        // purple: "#5932EA",
        blue: "#15134B",
        lightlemon: "#E8F9EE",
        "gray-2": "#F7F9FC",
        "gray-3": "#FAFAFA",
        whiten: "#F1F5F9",
        whiter: "#F5F7FD",
        boxdark: "#24303F",
        "boxdark-2": "#1A222C",
        strokedark: "#2E3A47",
        "form-strokedark": "#3d4d60",
        "form-input": "#1d2a39",
        "meta-1": "#DC3545",
        "meta-2": "#EFF2F7",
        "meta-3": "#10B981",
        "meta-4": "#313D4A",
        "meta-5": "#259AE6",
        "meta-6": "#FFBA00",
        "meta-7": "#FF6766",
        "meta-8": "#F0950C",
        "meta-9": "#E5E7EB",
        "meta-10": "#0FADCF",
        success: "#219653",
        danger: "#D34053",
        warning: "#FFA70B",
      },
    },
  },
  plugins: [],
};
